# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb6ab0b3ccda2fdc1d88666e959fc81e698c60f5bc9ea39b7d2d970abf43b520b8ac017c3ffb7dc494298df50277f12d3ea143d7ecdedad400b8c92601cb1806

test:
  secret_key_base: c892e9640aef82da20f710d3550f5eac9f57c88e1902fb737fc8cd7e6ccc82180c79a68be22e4828de54a65f5af3c48469eb3c4013fe1c79a6639afe2218c515

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
